# Dockerfile for development stage

# initalise base image from node version 16
FROM node:16

# add maintainer / contact details to container in form of key=value metadata
LABEL maintainer="svengerlach@me.com"

# set working directory inside container
WORKDIR /app

# copy package.json and package-loc.json from build-context into the container's working directory
COPY package*.json ./

# install all dependencies specified inside package.json at container compile-time
RUN npm install

# copy all files and directories from build-context into container's working directory
# excludes all files and directories specified in .dockerignore
COPY . .

# Expose container port 3000
EXPOSE 3000

# start the React server at container run-time (only when the container is spun up with "docker run ..."
CMD ["npm", "start"]
