# docker-compose yml file builds the development container
# yml file achieves the same as the following two CLI lines
# docker build -t react-image-dev -f secure-my-spot_client/Dockerfile.dev secure-my-spot_client/
# docker run -d -p 3000:3000 --name react-app-dev -v $(pwd)/src:/app/src:ro react-image-dev
# run this yml file from the CLI with: docker-compose -f docker-compose-dev.yml up -d

# specifies docker-compose version
version: "3.8"

services:
  # specify the React app service
  react-app:
    # specify configuration options at container build-time
    build:
      # specify build-context as the client folder
      context: .
      # specify the relevant dockerfile name inside the build-context
      dockerfile: Dockerfile.dev

    # given the build specifications, the image line specifies the tag of the newly created image
    image: react-app:dev

    # specify container name
    container_name: react-app-dev

    # mapping host port 3000 to container port 3000, such that any request on host port 3000 is passed to container port 3000
    ports:
      - "3000:3000"

    environment:
      # Without this env variable hot-reloading will not work
      # source: https://mherman.org/blog/dockerizing-a-react-app/
      - CHOKIDAR_USEPOLLING="true"

    # loading .env.dev required for local dev container and for testing run on Github actions
    # the latter requires .env.dev to be on Github repo
    # for production, ideally index.js reads Heroku config vars using dotenv but for some reason that does not work at
    # the moment
    env_file:
      - .env.dev

    # specify bind-mount volume such that any changes in the host's (build-context) src folder are reflected / replicated
    # inside the container -> amendments to the website are immediately reflected in the container, avoiding the need
    # to re-start the container after every change to the app

    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
