# Dockerfile for development stage

# initalise base image from node version 16
FROM node:16

# add maintainer / contact details to container in form of key=value metadata
LABEL maintainer="svengerlach@me.com"

# set working directory inside container
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# source: https://mherman.org/blog/dockerizing-a-react-app/
# source: https://stackoverflow.com/questions/59275686/dockerizing-node-js-app-what-does-env-path-app-node-modules-binpath
ENV PATH /app/node_modules/.bin:$PATH

# copy package.json and package-loc.json from build-context into the container's working directory
COPY package*.json ./

# install all dependencies specified inside package.json at container compile-time
RUN npm install

# copy all files and directories from build-context into container's working directory
# excludes all files and directories specified in .dockerignore
COPY . .

# Expose container port 3000
EXPOSE 3000

# start the React server at container run-time (only when the container is spun up with "docker run ..."
CMD ["npm", "start"]
