version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: react-image-prod
    container_name: react-app-prod
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
