# todo: consider if GitHUb pages approach should be replaced with Heroku pipeline workflow

name: deploy-to-heroku

on:
  push:
    branches:
      - main

# https://github.com/marketplace/actions/deploy-to-heroku
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: main
          usedocker: True
          docker_heroku_process_type: web
          stack: container
